### ISSUE TITLE
[packMP3] error: invalid conversion from ‘const char*’ to ‘char*’

### ISSUE THREAD

**Issue by szepeviktor** [packjpg/packJPG#2] opened 2015-02-19 00:35 UTC
On Debian/wheezy amd64:
```
$ make
g++ -c -o aricoder.o aricoder.cpp -I. -DDEV_BUILD -O3 -Wall -pedantic -funroll-loops -ffast-math -fsched-spec-load -fomit-frame-pointer
g++ -c -o bitops.o bitops.cpp -I. -DDEV_BUILD -O3 -Wall -pedantic -funroll-loops -ffast-math -fsched-spec-load -fomit-frame-pointer
g++ -c -o huffmp3.o huffmp3.cpp -I. -DDEV_BUILD -O3 -Wall -pedantic -funroll-loops -ffast-math -fsched-spec-load -fomit-frame-pointer
g++ -c -o packmp3.o packmp3.cpp -I. -DDEV_BUILD -O3 -Wall -pedantic -funroll-loops -ffast-math -fsched-spec-load -fomit-frame-pointer
packmp3.cpp: In function ‘void set_extension(const char*, const char*)’:
packmp3.cpp:6050:54: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
make: *** [packmp3.o] Error 1
```

After adding `-fpermissive` to the Makefile it compiles.

**Comment by szepeviktor** [comment] 2015-02-19 00:37
And because it is no win32:
```
#RES     = icons.res
```

**Comment by d0k3** [comment] 2016-01-22 15:55
This belongs into the (then not existing) packMP3 repo. I'll look after it!

**Comment by packjpg** [comment] 2016-01-22 16:59
I could not reproduce this error. I guess this is already fixed. Closing this for now, but you may want to check yourself, too!

**Closed by packjpg** 2016-01-22 16:59 UTC
Labels: bug
